name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout sources
        run: |
          mkdir studio-dev
          cd studio-dev
          repo init -u https://android.googlesource.com/platform/manifest -b studio-1.3-dev
      - name: Build
        run: |
           cd studio-dev/external/qemu
           cd android/scripts/
           chmod +x ./build-mesa.sh
           chmod +x ./build-qemu-android.sh
           ./build-mesa.sh
           ./build-qemu-android.sh
